all:
  hosts:
    front:
      ansible_host: 10.0.1.4
    back:
      ansible_host: 10.0.2.5
    db:
      ansible_host: 10.0.3.6
  vars:
    ansible_user: mateusz
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -i ~/.ssh/id_rsa mateusz@74.234.79.76"
