---
- hosts: all
  become: true

- hosts: front
  roles:
    - ../roles/frontend
    - ../roles/reverseproxy
- hosts: back
  roles:
    - ../roles/backend
# - hosts: db
#   roles:
#     - ../roles/database
